### ISSUE TITLE
Latest code not pushed to NPM

### ISSUE THREAD

**Issue by aj-may** [howdyai/botkit-storage-redis#11] opened 2016-10-04 15:40 UTC

**Comment by peterswimm** [comment] 2016-10-04 15:50
This should be fixed in the next major update (hopefully this week!)

**Comment by cms5x** [comment] 2016-10-14 15:55
(I assume this issue is the root cause of the problem I experienced): 
I Installed via npm, but found it lacked the recent change to add custom methods (beyond 'users', 'teams', 'channels'), cloning from gitHub solved that, but spent a little while pulling my hair out thinking it was something wrong on my end.  Looking forward to corrected npm deployment which will make automated deployments easier.

**Comment by peterswimm** [comment] 2016-10-14 16:21
Ive created a ticket for the team to take a look, will post an update when this is verified/fixed.

**Comment by bambielli** [comment] 2016-10-24 01:28
It would be great to get this published to NPM! I'd like to use the remove method.

**Comment by colestrode** [comment] 2016-10-24 15:02
This should be a minor version bump since new features were added. This should only take a few seconds, it would be great to have npm publishes as a part of merging into master. Since this is a small lib without long-range development in process, regularly merging seems like a good strategy.

I recommend using the `npm version` command, it handles bumping the version and tagging the repo. These are the commands I use for bumping libs (often I have the `git push` as a postpublish npm hook)

```
npm version minor
npm publish
git push origin master --follow-tags
```

**Comment by benbrown** [comment] 2016-11-07 18:15
@colestrode whoa that is super handy!

I am going to do this now.

**Comment by benbrown** [comment] 2016-11-07 18:16
Done! 1.1.0 is now live on npm.

Sorry for the delay.

**Closed by benbrown** 2016-11-07 18:16 UTC

**Comment by aj-may** [comment] 2016-11-07 19:01
Thanks @benbrown
